#!/bin/bash
declare -A VARS=( ["CLASS"]="Test" )

for VAR in "${!VARS[@]}"; do
    VAL=${1:-${VARS[$VAR]}}
    export $VAR=$VAL
    shift
done

#--------Begin here document-----------#
cat $TEMPLATE <<EOF
#!/bin/sh

. bump_version
rm ../output/$CLASS.swf
mxmlc \\
  $CLASS.as \\
  -metadata.creator ArtBIT \\
  -output ../output/$CLASS.swf

. play
EOF
#--------End here document-----------#
