#!/bin/bash
declare -A VARS=( ["CLASS"]="Main" )

for VAR in "${!VARS[@]}"; do
    VAL=${1:-${VARS[$VAR]}}
    export $VAR=$VAL
    shift
done

CLASS=${1:-"Test"}
#--------Begin here document-----------#
cat $TEMPLATE <<EOF
#!/bin/sh

open -a Flash\\ Player ../output/$CLASS.swf
EOF
#--------End here document-----------#
