#!/bin/bash
#--------Begin here document-----------#
cat $TEMPLATE <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Untitled</title>
    <meta name="author" content="Djordje Ungar">
    <!-- Date: '$(date)' -->
</head>
<body>
    <div id="main_wrapper">
    </div>
</body>
</html>
EOF
#--------End here document-----------#
